language: node_js
node_js:
- "10.8"

branches:
  except:
  - gh-pages

dist: trusty

addons:
  chrome: stable

before_script:
- yarn global add @angular/cli

cache:
  yarn: true
  directories:
  - node_modules

script:
- ng lint
- yarn test
- yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  target_branch: gh-pages
  on:
    branch: develop